#
CC = pgc++ -acc -ta=tesla:fastmath,cc70 # -Minfo=accel
CFLAGS = -O3
INCLUDES = -DUSE_OPENACC
DEPENDS = su3.hpp lattice.hpp mat_nn_openacc.hpp

bench_f32_openacc.exe: su3_nn_bench.cpp $(DEPENDS)
	$(CC) -DPRECISION=1 $(CFLAGS) $(INCLUDES) -o $@ su3_nn_bench.cpp $(LIBS)

bench_f64_openacc.exe: su3_nn_bench.cpp $(DEPENDS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ su3_nn_bench.cpp $(LIBS)

all: bench_f64_openacc.exe bench_f32_openacc.exe

clean:
	rm -f *openacc.exe
